/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./../components/Logo.vue')['default']
    PixelarticonsPower: typeof import('~icons/pixelarticons/power')['default']
    PixelarticonsZap: typeof import('~icons/pixelarticons/zap')['default']
    SharedSubtitle: typeof import('./../components/SharedSubtitle.vue')['default']
  }
}
